### ISSUE TITLE
(Navajo) Extend access object

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#281]
I would like the following information:

exitCode should preferably state how the script exited:
- normally
- validation failed
- programmatic break
- exception

size of the response (in bytes or chars) - this gives an idea how many results were found / how much information was parsed. For those webservices that vary in runtime by # of results.

log field should be something that can be written by an explicit command in the script (a la the debug command, perhaps it should be a separate command though) for when we need really fine-grained debugging.

In all cases the goal is that this information ends up in the access DB, without "requiring" that the script crashes to get it.

**Comment by cbrouwer** [comment]
Right now, the <debug value=""> should end up in the Access Object (under ConsoleOutput). 

Storing the byte size of the input/output message is actually quite hard, since it's not easy in Java to get the size of an object in bytes. Perhaps a simple hash would suffice, since this would allow to identify similar input/output?

**Comment by cbrouwer** [comment]
For now, there is no easy way to get a hash or something similar to identify a Navajo. Currently this would require traversing the entire Navajo document and all its messages and properties, which is too expensive to perform on every Navajo to be stored.
Given the functionality already added previously, I consider this issue closed.
