### ISSUE TITLE
(Tipi) Overlay doesn't work with onValueChanged event?

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#294]
The new feature ```overlay="transparent"``` in tipi doesn't seem to work with onValueChanged event(s). Example is in ```teamsNewLocalTeamPersonDialog``` (SLC > Wedstrijdzaken > Teams > Lokale teams > double-click a team > Alle deelnemers tab > +-icon on the bottom right > change the Role)

**Comment by kharybdys** [comment]
Note that I also tried to define a localMethod and call that from within the onValueChanged. That didn't work either.

**Comment by kharybdys** [comment]
Change is available in the master branch

**Comment by cbrouwer** [comment]
The current onValueChanged implementation is to run synchronous in the event thread. This means that, although the overlay is added to the window/dialog, it's not visible until the event is finished, at which point its immediately removed again. 
Withouth changing the OnValueChanged synchronous behavior (with all its possible side-effects), this cannot be changed.

**Comment by kharybdys** [comment]
Note that there is a very good reason why onValueChanged is run in the event thread (but I can't remember why off the top of my head), so we'll have to live with not having an overlay in that situation I guess.

**Comment by cbrouwer** [comment]
Is is now possible to specify the `handleValueChangeSync` attribute of a property. Setting this to 'false' handles the `onValueChanged` event of a property asynchronous - the UI will stay responsive and if specified an overlay will also be displayed.

I strongly recommend only using this in combination with an overlay panel, since this prevents the user from changing values while the `onValueChanged` event is still running.
