### ISSUE TITLE
Fix WrapCollector and DefaultNavajoWrap dependency

### ISSUE THREAD

**Issue by aschoneveld** [Dexels/navajo#321]
DefaultNavajoWrap has a dependency with WrapCollector. Currently this is resolved by a static construction which is not desirable. 
Solution: create a DefaultNavajoWrapFactory OSGi DS that has WrapCollector DS as dependency. The factory can create DefautlNavajoWrap objects that have the proper WrapCollector dependency.

**Comment by aschoneveld** [comment]
see #318

**Comment by cbrouwer** [comment]
WrapCollector is used from DefaultNavajoWrap. This Wrap is created from three possible entry points: dbreplication.DatabaseTransaction , HazelcastServiceAnswer/Request and HazelcastBefore/AfterWebServiceRequest. The DatabaseTransaction will be looked at in #323. 
The latter two are eventually initialized from a HazelcastTribeManager. Since the TribeManager is a dependency for the WrapCollector, effectively this means it's not possible to create a DefaultNavajoWrap instance without having a WrapCollector.
