### ISSUE TITLE
OSGi-ify com.dexels.navajo.enterprise.dbreplication

### ISSUE THREAD

**Issue by cbrouwer** [Dexels/navajo#323]
com.dexels.navajo.enterprise.dbreplication needs some refactoring to play nicer in an OSGi environment: remove static references and make (better) use of OSGi services.

**Comment by aschoneveld** [comment]
Fixed

**Comment by kharybdys** [comment]
Looks like the Dispatcher now has an undocumented dependency on the sharedMemoryStore.
I have the navajo.enterprise.webservicelistener.registry component unsatisfied as well as the navajo.enterprise.listenerstore component because I have turned of the sharedMemoryStore. System starts up and provides me with continuations, but trying to call a webservice results in a NPE on line 1037 in the Dispatcher.
```
                    Navajo useProxy = WebserviceListenerFactory.getInstance().beforeWebservice(rpcName, access);
````
