### ISSUE TITLE
Output entity not ok

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#331]
In certain entity definitions, the output is not as it should be.

This is an example of what it should be:
{
    "Officials": [
        {
            "PersonId": "DJ4S086",

And this what it is, but shouldn't be:
[
  {
    "PersonId": "DJ4S086",

BTW: the documentation does show the correct outputformat

**Comment by cbrouwer** [comment]
This is a result of the output from the webservice. In this specific example, the entity definition is as follows:
```
<message name="Officials">
    <message name="Officials" type="Array">
    ...
    </message>
 </message>
```

However, the webservice returns:
```
<message name="Officials" type="Array">
...
</message>
```

Since the message names are matching, the merge/filter action cannot perform a proper masking/filter action, and thus the output is a top-level array.

This can be fixed by returning a message that matches the entity definition.

**Comment by eversteeg** [comment]
Ik weet nog niet wanneer ik hieraan toekom, dus niet live zetten zonder 
overleg aub. ;-)

Op 19-11-2015 om 10:43 AM schreef Chris Brouwer:
