### ISSUE TITLE
IfElse function still evaluates false part

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#343]
When the condition in the IfElse function results in false, then the true part still gets to be evaluated and therefore might result in an error.
For instance while checking for existing property which results in false should not trigger the true part.

**Comment by eversteeg** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<navascript author="Erik Versteeg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.navajo.nl/schemas/navascript.xsd">
    <methods>
        <method name="vla/sportlinkkernel/member/transfer/ProcessTestIfElse"/>
    </methods>

    <message name="TestArray" type="array">
        <message name="TestArray" type="array_element">
            <property name="Id">
                <expression value="0"/>
            </property>
        </message>
    </message>
</navascript>
```

**Comment by eversteeg** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<navascript author="Erik Versteeg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.navajo.nl/schemas/navascript.xsd">
    <map.arraymessage>
        <field name="emptyMaps">
            <map ref="/TestArray">
                <debug value="'**************** ' + ?[Id]"/>
                <debug value="'**************** ' + ?[BenErNiet]"/>
                <debug value="'**************** ' + IfElse( ?[BenErNiet], [BenErNiet], 'LekkerPuh' )"/>
            </map>
        </field>
    </map.arraymessage>
</navascript>
```

**Comment by cbrouwer** [comment]
The compiler does not have knowledge what a Navajo function does with its parameters. In this case, depending on the first argument, only one of the two remaining parameters are used. However, since the compiler does not know this, all parameters are evaluated when passing them on to the function.

A possible solution would be to introduce a different type of Navajo functions, where parameters are not evaluated at all, but instead that this evaluation is left over to the function itself. Due to the limited use case for this and the additional complexity such a different class of functions would introduce, this will not be implemented now.
