### ISSUE TITLE
(Tester interface) Seems to crash when downloading an array message

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#354]
Error according to Firebug:

```

ReferenceError: property is not defined


property.children('option').each(function() {


csvexport.js (line 29, col 21)
```

I was executing matchreport/proxy/ProcessQueryMatchPersons on knzb production with custom input:

```
<message name="MatchForm">
    <property name="MatchId" type="integer" value="158722"/>
    <property name="MatchRole" type="string" value="HOMECLUB" />
</message>
```

**Comment by DimitrisD** [comment]
*use 212518 as Matchid for testing

**Comment by DimitrisD** [comment]
Found the issue. Fixed it.

But, because in csvexport.js, we create the header of the csv file from the definition message, and 
 becauese the order (and not only) of the properties on the definition message might be different from the order (and probably type as well)  of the properties in the array_elements messages, the csv has not a correct format. 

My thought on this is, that we should not take into consideration the definition message at all, when we are creating the csv.

**Comment by DimitrisD** [comment]
I can see that there is this issue https://github.com/Dexels/navajo/issues/355 which implies that even when there's a definition message, the ordering is incorrect.

Maybe, if we fix this issue, the thing that i'm talking about wouldn't come up, but still is there a possibility that the message might have more properties than the definition message?
