### ISSUE TITLE
(Tipi) When a webservice fails with a network error during an onInstantiate event, do...

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#376]
* show a specific error message.
* dispose the instantiating component.

**Comment by cbrouwer** [comment]
See https://github.com/Dexels/navajo/commit/d5d632136573d6e957e2c01f54e98d85125144e7.

This commit disposes the component when an exception occurs during the OnInstantiate. The error message on connection errors is handled by NavajoClient + validation.properties, which is OK for now I think.

We have to decide whether to specifically filter out connection errors, or to dispose the component also when *any* type of 'unexpected' exception occurs. 
Since these exceptions stop the methods/blocks, there are most likely actions that have not completed yet. Therefore, I would suggest closing the component on any exception during the OnInstantiate.
