### ISSUE TITLE
(Tipi) When instantiating a data component...

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#377]
If a component listens to webservice A and the system has a result of that webservice cached, load with that data (including triggering an onLoad event). Probably as final or near final step on the instantiation of the component that listens.

**Comment by cbrouwer** [comment]
Due to the fact that Tipi applications cache their Navajo's indefinitely, this feature should be handled carefully. 

When opening a window and for whatever reason the new Navajo is not loaded, one doesn't want totally different data (from another entity previously opened)  showing up. Thus, we should be sure that if something goes wrong, the window is closed or at least the action of loading an existing Navajo is prevented. This is related to #376.
Also, we should be sure that this doesn't clash with a non-standard instantiate flow, where the Navajo is loaded out of sync from the Instantiate event. For example, if the callService is a separate action after the Instantiate, this would then result in a double onLoad (since when finishing the OnInstantiate there is no Navajo yet).

I can see the added value for this feature, but there are also scenario's where this might result in weird/unwanted behaviour (that is not immediately obvious when looking at the Tipi code). Do the pros outweigh these cons?

**Comment by kharybdys** [comment]
This can be handled by following the following paradigm:
In the opening event
```
<onActionPerformed>
   <callService/>
   <instantiate/>
</onActionPerformed>
````
In the onInstantiate of the instantiated component:
```
<onInstantiate>
   ...
   <reloadNavajo/>
   <dialog.show/> or <window.toFront/>
</onInstantiate>
````

No changes are required to the libraries
