### ISSUE TITLE
IsDirty function doesn't check textarea

### ISSUE THREAD

**Issue by eversteeg** [Dexels/navajo#383]
When using the function IsDirtyComponent( {component:/~} ) to check if the user should get a save question, properties of the memo/textarea type are skipped.
This probably applies to the tipi clearDirty tag as well...

**Comment by eversteeg** [comment]
The same issue applies to other properties as well, but with the restriction that it only applies while updating a property and clicking directly on the x (close window).
So you edit one property and then click on close window. The IsDirty check doens't see the change yet. Only after lostFocus, the check fires correctly.

**Comment by cbrouwer** [comment]
I am seeing that the setDirty is also triggered when losing focus on a textfield/memo. Considering your second comment, am I correct in assuming this issue is actually about that the isDirty flag is only set after losing focus, regardless of the component?

Changing this is somewhat complicated. Right now this isDirty flag is set when the navajo property behind the tipi (swing) component actually changes of value. Losing the focus is one of the possible triggers for this. 
To change this would mean a complete different implementation of the event handling for all tipi property components. Furthermore updating the Navajo property on every keypress might also bring with a performance penalty. Finally, I can imagine there are parts in the application where changing the property while the user is still typing might result in unexpected/unwanted behaviour. 

The behaviour I am seeing on OS X btw is that the isDirty flag is indeed set when clicking the 'close' button. Perhaps it's a problem of order: the isDirty check is done before the focus is actually lost when closing the window?

**Comment by eversteeg** [comment]
An example: open the personwindow, change/add some text in a random field and directly close the window. No question will be asked.
Now do the same but tab out of the field. The onFocusLost will cause the isDirty to be set.
I understand that you don't want to apply this to a onKey event, but the first part of this example is a pretty straight forward usecase which is not supported right now.

**Comment by DimitrisD** [comment]
@cbrouwer We should close this issue.

**Comment by cbrouwer** [comment]
Fixed in 2448ea324f83d5119d020177a6bf1db32adeeb5b
