### ISSUE TITLE
(Navajo) Array definition message makes a memo property into a tipi property

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#395]
Compare the response of
````
	<message name="Marte" type="array">
			<message name="Marte" type="array_element">
				<property name="RegistrationId" type="integer" direction="out">
					<expression value="1"/>
				</property>
				<property name="MemoProperty" type="memo" direction="in">
					<expression value="ToMemo(null)"/>
				</property>
			</message>
		</message>

````
with
````
	<message name="Marte" type="array">
		<message name="Marte" type="definition">
			<property name="RegistrationId" type="integer" direction="out"/>
			<property name="MemoProperty" type="memo" direction="in"/>
		</message>
			<message name="Marte" type="array_element">
				<property name="RegistrationId" type="integer" direction="out">
					<expression value="1"/>
				</property>
				<property name="MemoProperty" type="memo" direction="in">
					<expression value="ToMemo(null)"/>
				</property>
			</message>
		</message>
````
and
````
	<message name="Marte" type="array">
		<message name="Marte" type="definition">
			<property name="MemoProperty" type="memo" direction="in"/>
		</message>
			<message name="Marte" type="array_element">
				<property name="MemoProperty" type="memo" direction="in">
					<expression value="ToMemo(null)"/>
				</property>
			</message>
		</message>
````

The first and last give MemoProperty a type of "memo" as it should, the second gives it a type of "tipi"

**Comment by cbrouwer** [comment]
What exactly am I looking at? I am not sure what exactly is happening, where this is taking place, and what is wrong and what isn't.. A bit more context is welcome.

**Comment by kharybdys** [comment]
Run each of these as a script (or put them into one) then compare the type of the property "MemoProperty" as given in the response. Only the second gives the expected type of memo, the others give a type of tipi which is unexpected and has to be wrong

**Comment by kharybdys** [comment]
This issue has to be fixed before the KTI project can deliver (~ april 2017)

**Comment by cbrouwer** [comment]
When creating a property, Navajo checks whether the property already exists (MappingUtils.java:264, `ref.getProperty()`). At BaseMessageImpl.java in `getPropertyByPath()`, there is some logic that, if we have a definition message, we return this property as a match, even if such a property does not exists in our current message. As a result, a different path is taken when setting the value of the property, where `setType()` was not called anymore (as opposed to when creating a new property from scratch, where `setType()` is always called after setting the value).
The second issue is that a memo-type is not supported as a primitive type in properties (until 5ac93958e31955eb4adc8da00b666a3e4ac6f52f). 
The combination of these caused the property type to become "tipi" (which is the default property type if nothing else matches).

The fact that the 3rd example did work is rather peculiar. It turns out that the logic, when checking whether a newly added property already exists, only goes there is we have at least 1 property in our current message. Otherwise the propertyList is null, and we return immediately from `BaseMessageImpl.getPropertyByPath()`. 
This seems to be plain wrong or at least undesirable, but changing this might cause existing scripts to work differently. Thoughts?
