### ISSUE TITLE
Navajo function to add Date and ClockTime

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#402]
There's a need to add dates and clocktimes, which can be done with date parse/format functions and string manipulation, as shown in this example:

ParseDate(FormatDate([CalendarDate], 'yyyy MM dd') + ' ' + ToString([EndTime]), 'yyyy MM dd HH:mm:ss')

It is possible to make mistakes in expressions like above, for example: 

ParseDate(StringFunction('replaceAll', ToString([CalendarDate]), '00:00:00', ToString([EndTime])), 'EEE MMM dd HH:mm:ss zzz yyyy')

This expression is almost correct, but on the day of daylight saving change, this will go wrong because the original date + time is before the daylight saving change, and the 'replaced' version is after daylight saving change.

A generic Navajo function would prevent this and makes coding and reading code easier.

**Comment by roelofkemp** [comment]
Not urgent at the moment!

**Comment by DimitrisD** [comment]
If I get you correctly, what you need is a DateTime(regex) Navajo function, which returns the Date + Time styled by the regex you provided as a parameter?

**Comment by kharybdys** [comment]
What do you do if the Date pass in has a time of its own? I would suggest to throw an exception.

**Comment by DimitrisD** [comment]
Hmm. Some thoughts on the above.

All java date objects encapsulate a time object. If you don't define it then it's 00:00:00. Which means that all passed dates in that function contain a time. The purpose of the function would be to overwrite the encapsulated time and return a date object which has the time that was sent as an argument. 
  
Also, the navajo function date, returns a date object of the format "yyyy-MM-dd". Which means that the java date object that is used has time 00:00:00.  

The only way that i can think of sending a date object which has defined time (not 00:00:00) in this function, is if we pass as a first argument the value : FormatDate(Date('2011-12-31'),'yyyy-MM-dd HH:mm:ss'). In this case indeed the object that would go into the DateAppendClockTime function would have a "specific" time.

But still, the above scenario cannot be somehow checked since all date objects have time :S Any ideas or input would be appreciated.

**Comment by cbrouwer** [comment]
Indeed all Date objects have a time aspect.
I would say if you use the function to set the time on a date object, you are not interested in the time of the original date. 
@kharybdys do you have a use case where you want to use this function, but would not want to overwrite an existing time (and possibly throw an exception and thus crashing the running script)?
