### ISSUE TITLE
(Tester) JSON to TML doesn't correctly make a float if required

### ISSUE THREAD

**Issue by kharybdys** [Dexels/navajo#440]
The following message, properties Priority and PriorityMultiplier should become a float but became an integer instead:
```
{     "Whatever" : 
{
      "Assign" : true,
      "IgnorePreferences" : false,
      "FacilityIdentifier" : "DK3M604",
      "FacilityName" : "Sportpark De Haamen",
      "ClubName" : "Cheetahs",
      "ClubIdentifier" : "DH6H46P",
      "ElevenTeamCount" : 0,
      "SevenTeamCount" : 0,
      "TeamCount" : 0,
      "TotalHalfFields" : 4,
      "TotalFullFields" : 2,
      "SmallGoalCount" : 8,
      "FieldCount" : 2,
      "Priority" : 0.0,
      "OtherOrgPreference" : false,
      "PlayDay" : "SUN",
      "PriorityMultiplier" : 1.0,
      "TotalFacilityFields" : 2,
      "TotalOrganizationFacility" : 2
    }
}
````

**Comment by DimitrisD** [comment]
This cannot be fixed easily.

In order to transform the json to tml, we use the javascript function **JSON.parse()**, which given a string creates a JSON object.

Javascript doesn't have integers or floats, it only has numbers. That's why the JSON.parse() function, parses the 0.0, as a number, who's representation is 0, which is an "integer".

In order to actually fix this we need to create our own parsing mechanism, something that would require a great amount of time for something that that is a helper (?) functionality mechanism to quickly make a tml out of a json.

At this moment, the developer who is using this helper functionality should have this restriction in mind when converting messages with number properties. 

A recommendation for this issue could be an alert that is fired when we are transforming a json to a tml and we detect a property number.
