### ISSUE TITLE
tipi table does not show when defaultVisible argument is missing in column

### ISSUE THREAD

**Issue by jposthumus** [Dexels/navajo#444]
When the argument defaultVisible is missing in the column within a tipi table, the entire tipi table is not shown.

The default visible argument should be optional.

**Comment by cbrouwer** [comment]
The current solution seems to have changed columns to be default visible if not specified otherwise. Is that what was intended?

**Comment by DimitrisD** [comment]
Yeah

**Comment by cbrouwer** [comment]
why?
This issue is about that the `defaultVisible` attribute should be optional (as it currently is afaik); not that the default value should be changed, right? 
I counted roughly 100 columns where this attribute is not specified - changing the default without changing existing definitions will cause all of those columns to suddenly be visible.

**Comment by DimitrisD** [comment]
I discussed it with @jposthumus  and @eversteeg and they all agreed that they wanted it by default to be visible. All of the existing scripts contain the tag (which means that the functionality of the old ones will be the same) but they implemented a lot of new ones that they didn't add the tag on any column, and they were expecting it to be visible, but because by default it was false, the table was not shown (thus this issue was created). So this issue wasn't a bug, it was a functionality change on the default value of this tag.
