### ISSUE TITLE
DatePicker support multiple locale

### ISSUE THREAD

**Issue by Michiatdexels** [Dexels/navajo#455]
it should be possible to change the locale of the datepicker to support multiple languages

**Comment by cbrouwer** [comment]
Related to #434? Not sure which DatePicker we are talking about here.

**Comment by Michiatdexels** [comment]
![screen shot 2018-05-18 at 08 33 51](https://user-images.githubusercontent.com/31535620/40219580-51f5446e-5a76-11e8-883e-b1ccb5790a87.png)
This datepicker.

**Comment by kharybdys** [comment]
Note that the issue here is in the bit of libraries that are "sort of" shared with the Client libraries so the solution ought to be similar and perhaps worked on in parallel.
Also note that the problem is twofold. It's the DatePickerDialog but also the text displayed in the date field itself. And then we need to make sure the date is correctly recognized if we're sending it from a UI to the server.

**Comment by cbrouwer** [comment]
The component in question: tipi/com.dexels.navajo.tipi.swing.client/src/com/dexels/navajo/tipi/swingclient/components/calendar/CalendarPickerDialog.java

**Comment by kharybdys** [comment]
And tipi/com.dexels.navajo.tipi.swing.client/src/com/dexels/navajo/tipi/swingclient/components/DatePropertyField.java
