### ISSUE TITLE
dash in folder for entities

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navajo#481]
Both the dependency analyzer and the entityDocumentation seem to dislike a dash '-' in the path of an entity

**Comment by DimitrisD** [comment]
This turns out to be a different issue. Seems like scripts under folders with dash (hyphen) aren't compiled. The issue lies in tsl compiler. Investigating further.

**Comment by DimitrisD** [comment]
This operation is not and won't be supported, because the folder name is translated into a package name. If that package name contains a dash or a hyphen inside it, it will not be able to be compiled by the tsl compiler.

If you want to achieve the dashes/hyphens in urls, you can do it by using the entity mapping functionality.
