### ISSUE TITLE
sendThrough field in NavajoMap is not set in setter

### ISSUE THREAD

**Issue by gballintijn** [Dexels/navajo#518]
The `sendThrough` field in the `NavajoMap` is not set in `setSendThrough()` method; the method only copies some messages. The field is, however, used in the `prepareOutDoc()` method in two conditions (but is always false).

**Comment by gballintijn** [comment]
The setter also ignores the parameter passed in. It always performs the sending through operation (i.e., copying messages).

**Comment by kharybdys** [comment]
Note that due to the way things are implemented, combinations of sendThrough, useCurrentOutDoc, useCurrentMessages, copyInputMessages and the use of a createProperty tag cause unexpected effects (timing is a thing). For example (from memory), using copyInputMessages and a createProperty tag for the same message and a property in there, results in the value from copyInputMessages winning over the value from createProperty. This is not what is expected, at least by me.

Interesting read about NavajoMap: https://github.com/Dexels/navajo/wiki/Passing-on-messages-through-NavajoMap

**Comment by kharybdys** [comment]
See also #494

**Comment by gballintijn** [comment]
Using the branch "Issue-518-sendThrough-field-NavajoMap" for the fix.

**Comment by gballintijn** [comment]
Added test code in same-name branches in the `navajo.example` en `navajo-example-test` repositories.

**Comment by gballintijn** [comment]
Deployed as com.dexels.navajo.adapters 2.7.52 on test.
