### ISSUE TITLE
Examine and improve the release(full).sh scripts

### ISSUE THREAD

**Issue by gballintijn** [Dexels/navajo#530]
It appears that the releasefull.sh scripts jumps a version number when using the default values, leading to even numbered release numbers. This is probably caused by not properly distinguishing snapshot and release version. It would be better if the numbers would increment normally.

**Comment by billgemist** [comment]
Yes the even numbers are the bundle release version and the odd number is the snapshot version, this is the rule if I got it correctly. Generally, the odd numbers they have a "-SNAPSHOT" addition in the name, I'm not sure if all the bundles do. So, I think is a call that we have to decide if we are going to leave it as is or not, because the even(for the bundles) and odd(for the snapshots) may conflict with other procedures too.

**Comment by gballintijn** [comment]
Not important enough; we might want to revisit this in the future.
